@startuml administração
!include users.puml

package "Administração e Infraestrutura" {
  ' 001 (mas seria apenas visualizar)
  (Visualizar logs) as visLog
  ' 003
  (Manter políticas de logs) as mantPolLog
  ' 005
  (Configurar rotinas de backup) as confBack
  ' 010
  (Visualizar saúde\ndo sistema) as visSau
  ' 011
  (Reportar erro) as repErr
  ' 012
  (Notificar erro crítico) as notifErr

  ' relacionamentos
  adm -- (visLog)
  adm -- (mantPolLog)

  adm -- (confBack)

  ges -- (visSau)

  us -- (repErr)
  
  adm -- (notifErr)
}
@enduml