@startuml autenticação
!include users.puml

package "Controle de acesso" {
  ' 001, 004
  (Fazer login) as login
  ' 003
  (Visualizar\ntentativas de\nentrada falhas) as visCda
  ' 005
  (Manter políticas\nde expiração/renovação\nde senhas) as polSen
  ' 008
  (Encerrar sessão) as logout
  ' 009
  (Bloquear acesso) as bloq
  ' 006
  (Encerrar sessão\nde outro Usuário) as endSes

  ' relacionamentos
  (logout) <|-- (endSes)

  us -- (login)

  us -- (visCda)

  adm -- (polSen)

  us -- (logout)
  adm -- (endSes)

  note "{Se mais de uma tentativa falha}" as n1
  (login) <.. n1 : <<extend>>
  n1 .. (bloq) 
}
@enduml