@startuml
left to right direction

actor Usuario
actor Contador
actor Gerente

Usuario <|-- Contador
Usuario <|-- Gerente

rectangle "Modulo de Relatorio - Consultas" {
  Contador -- (Consultar Histórico de Simulações)
  Gerente  -- (Consultar Histórico de Simulações)

  (Consultar Histórico de Simulações) ..> (Aplicar Filtros) : <<include>>
  (Consultar Histórico de Simulações) ..> (Visualizar Simulação) : <<include>>

  (Aplicar Filtros) <|-- (Filtrar por Cliente)
  (Aplicar Filtros) <|-- (Filtrar por Período)
  (Aplicar Filtros) <|-- (Filtrar por Regime)

  (Consultar Histórico de Simulações) ..> (Limpar Filtros) : <<extend>>
  (Consultar Histórico de Simulações) ..> (Buscar por Nome do Cliente) : <<extend>>
  (Consultar Histórico de Simulações) ..> (Ordenar Lista) : <<ex
