@startuml
left to right direction

actor Usuario
actor Contador
actor Gestor

Usuario <|-- Contador
Usuario <|-- Gestor

rectangle "Modulo de Relatório" {
  Contador -- (Exportar Resultados)
  Gestor   -- (Exportar Resultados)

  (Exportar Resultados) ..> (Selecionar Opções de Exportação) : <<include>>
  (Exportar Resultados) ..> (Gerar Arquivo) : <<include>>
  (Exportar Resultados) ..> (Realizar Download) : <<include>>

  (Selecionar Opções de Exportação) <|-- (Exportar Excel Detalhado)
  (Selecionar Opções de Exportação) <|-- (Exportar CSV Simples)

  (Exportar Resultados) ..> (Exportar Múltiplas Simulações) : <<extend>>
  (Exportar Resultados) ..> (Agendar Exportação Recorrente) : <<extend>>
}

@enduml
