@startuml geral
!include users.puml
left to right direction

rectangle SST {
  package "Administração e Infraestrutura" as ai
  package "Controle de Acesso" as ca
  package "Gestão de Usuário" as gu
  package "Atualização de Legislação e Alíquotas" as ala
  package "Relatórios e Dashboards" as rd
  package "Importação de Dados e Validações" as idv
  package "Cálculo e Simulação Tributária" as cst

  ' Users to modules
  us -- ai
  adm -- ai
  ges -- ai

  us -- ca
  adm -- ca

  co -- cst
  ger -- cst

  co -- rd
  ger -- rd

  us -- gu
  adm -- gu
  tec -- gu
  ger -- gu

  co -- idv
  ger -- idv
}

@enduml