@startuml gestão
left to right direction

!include users.puml

package "Gestão de usuários" {
  ' 001
  (Manter usuário) as mantUs
  ' 002
  (Manter associado) as mantAss
  ' 005
  (Gerenciar perfil) as gerenPf
  ' 014
  (Visualizar\n informações de\nassociado e gerente\ntemporariamente) as visInfo

  ' relacionamentos
  (mantUs) <|-- (mantAss)

  adm -- (mantUs)

  ger -- (mantAss) 

  us -- (gerenPf)

  tec -- (visInfo)
}
@enduml