@startuml geral
left to right direction

rectangle SST {
  package "Administração e Infraestrutura" as ai
  package "Controle de Acesso" as ca
  package "Gestão de Usuário" as gu
  package "Atualização de Legislação e Alíquotas" as ala
  package "Relatórios e Dashboards" as rd
  package "Importação de Dados e Validações" as idv
  package "Cálculo e Simulação Tributária" as cst

  cst <.. rd
  idv <.. cst
  ala <.. cst

  ca <.. gu
  ca <.. ai
  ca <.. cst
  ca <.. ala
  ca <.. rd
  ca <.. idv
}

@enduml