@startuml autenticação
!include users.puml

package "Controle de acesso" {
  (Fazer login) as login
  (Notificar\ntentativas de\nentrada falhas) as notifCda
  (Manter políticas\nde expiração/renovação\nde senhas) as polSen
  (Encerrar sessão) as logout
  (Bloquear acesso) as bloq
  (Encerrar sessão\nde outro Usuário) as endSes

  (logout) <|-- (endSes)

  us -- (login)

  us -- (notifCda)

  adm -- (polSen)

  us -- (logout)
  adm -- (endSes)

  note "Se mais de uma tentativa falha" as n1
  (login) <.. n1
  n1 .. (bloq) : <<extends>>
}
@enduml