@startuml visualizar status do modulo
|Gestor|
start
:Inserir módulo desejado;

|Sistema|
:Buscar módulo;

if (Módulo encontrado?) then (sim)
  :Apresentar status do módulo informado;
else (não)
endif

stop
@enduml